= Design Proposal: Pablo Fees & Staking Rewards Distribution
:toc:
:toclevels: 4
:sectnums:
:sectnumlevels: 4

== Abstract

This document proposes the Pablo distribution(token and pool trading fees) mechanism while considering various options and capturing the discussions about the subject.

`TODO summarise the mechanism`

== Background

=== PBLO Token Initial Distribution

According to the http://link[tokenomics design] the Pablo is supposed to be distributed as follows,

* Ecosystem fund - x
* Farming rewards - y
* LBP Auction - z
* ...

TODO fill above with details from the original sheet.

The farming rewards are incentives for liquidity provider(LP)s who stake their LP tokens for Pablo pools. How much reward is allocated as incentive for each pool is to be decided by governance.

=== Pool Fees

Composable intends to distribute some percentage of the swap(transaction) fees captured by the pools in Pablo dex pallet as rewards to users who stake their `PBLO` tokens using the staking-rewards pallet interface. The idea is to incentivize the continuous owning of the staked `PICA` and `PBLO` to earn these yields which increases the value of the ecosystem overall by increasing the desirability of the staked assets.

At the time of writing Pablo has the following fee parameters other than for liquidity bootstrapping pools(LBP) which do not charge fees,

. LP Fee - A percentage of the trading fee that is distributed to liquidity providers based on the number of liquidity provider(LP) tokens they minted at the time of providing the liquidity.
. Pool Owner Fee - A percentage of the trading fee that is distributed to the pool owner.

==== LP Fee Distribution

This is yet to be implemented in Pablo, hence the idea is that it can be addressed in the context of this proposal.

== Use Cases

Following is a summary of use cases omitting the UI specific use cases for brevity.

[plantuml,images/pablo-distribution-users,png]
----
skinparam usecase {
BackgroundColor<< Staking >> YellowGreen
BorderColor<< Staking >> YellowGreen

ArrowColor Olive
}
left to right direction
actor LP as lp
actor Governance as g
actor PicaStaker as s
actor PabloStaker as p

package Picasso {
    package Pablo {
        usecase "Stake PBLO" as UC2 <<Staking>>
        usecase "Earn PBLO Reward" as UC4 <<Staking>>
        usecase "Stake LP Token" as UC5 <<Staking>>
        usecase "Earn Pablo LP\nTrading Fees" as UC6
        usecase "Earn Pablo Protocol\nTrading Fees" as UC13 <<Staking>>
        usecase "Set Pool Protocol\nFee Percentage" as UC7
        usecase "Set PBLO Reward Rate" as UC9
        usecase "Set PBLO Reward\nAllocation Percentage" as UC12
    }
    usecase "Stake PICA" as UC1 <<Staking>>
    usecase "Earn PICA Reward" as UC3 <<Staking>>
    usecase "Earn Other\nToken(s) Reward" as UC10 <<Staking>>
    usecase "Set PICA Reward Rate" as UC8
    usecase "Set PICA Reward\nAllocation Percentage" as UC11
}

p -up-> UC2
p -up-> UC4
p -up-> UC13
s --> UC1
s --> UC3
s --> UC10
lp --> UC4
lp --> UC5
lp --> UC6
g -up-> UC7
g -up-> UC8
g -up-> UC9
g -up-> UC11
g -up-> UC12
----

== Requirements

=== Pablo Liquidity Providers

. LPs MUST be able to stake their LP tokens to earn rewards allocated for a particular pool.
.. Rewards can be in terms of PBLO, PICA or any other tokens.
.. Same pool can receive multiple types of tokens as rewards.
. The system MUST support accumulating the LP share of Pablo trading fees.
. Pablo trading fees(LP fee part) MUST be disbursed according to LP token share of each LP. Fees are accumulated towards increasing liquidity in a pool while allowing LPs to redeem the fee share with their LP tokens at a preferred time.

=== PBLO Stakers

. System MUST allow staking of PBLO. This must be implemented through the fNFT mechanism with multiple time period unlocks being possible for users.
. The system MUST accumulate the rewards share for PBLO holders who stake PBLO token, out of the PBLO supply allocated for them.
. The system MUST support accumulating the (stakers) reward part of the Pablo trading fees.
. The system must support rewards being distributed on granular basis - e.g every 6 or 12 hours.
. The users MUST be able to claim the rewards once distributed.
. The system SHOULD support rewards in the form of fNFTs.

=== PICA Stakers

. System MUST allow staking of PICA. This must be implemented through the fNFT mechanism with multiple time period unlocks being possible for users.
. The system MUST accumulate the rewards share for PICA holders who stake PICA token, out of the PICA supply allocated for them.
. The system MUST support accumulating any token rewards other than PICA for PICA stakers.
. The system must support rewards being distributed on granular basis - e.g every 6 or 12 hours.
. The users MUST be able to claim the rewards once distributed.
. The system SHOULD support rewards in the form of fNFTs.

=== Pablo Governance
. Governance MUST be able to set the PBLO token reward allocation.
. Governance MUST be able to set the Pablo LP reward proportion for each Pablo LP token(i.e Pool) out of PBLO or other token reward allocation. This is to incentivize providing liquidity to required pools as decided by governance.
. Governance MUST be able to adjust the PBLO reward rate(eg: daily) based on the incentivization strategy.
. Pablo pool protocol fees(for rewarding protocol stakers) SHOULD be configurable as a percentage of the pool owner fee.

=== PICA Governance
. Governance MUST be able to set the PICA token reward allocation.
. Governance MUST be able to adjust the PICA reward rate based on the incentivization strategy.

=== Technical Requirements
. The system MUST allow accumulation and mapping of rewards shares of multiple assets types(Eg: PBLO, KSM) to staked position(fNFT) type defined by another asset type(eg: PICA).
. The system MUST support transfer of rewards using staking-rewards pallet to necessary fNFT types.
. The system SHOULD support converting a reward accumulated in one asset type to another based on a preferred reward asset type configuration. Eg: Given a reward accumulated is in Acala it should be able to convert that to one of PBLO or PICA using the Pablo DEX pools.
** This is to handle cases where a Pablo pool fees are in a different asset type than what is preferred.

== Method

=== System Overview

[plantuml,images/pablo-distribution-verview,png]
----
skinparam component {
  backgroundColor<<exists>> LightGreen
}

node "Pallet-Staking-Rewards\n(Pallet-Rewards?)" {
    StakingReward - [Reward Logic]
    Staking - [fNFT Storage/Logic]
    Node "BatchProcess" {
        [RewardDisbursementHook]
        [RewardsConfig] --> [RewardAccumulationHook]
    }
}

[fNFT Storage/Logic] <<exists>>
[RewardDisbursementHook] <<exists>>

node "Pallet-Pablo" {
    [Pool] --> StakingReward : transfer\ntrading fees\nfor PBLO stakers
    [Pool] --> Staking : stake LP tokes
    [Pool] --> [Pool] : accumulate LP\ntrading fees
    [FeeConfig] --> [Pool]
}

[Pool] <<exists>>

node "Pallet-Vesting" {
    StakingReward --> [VestedTransfers]: Make vested transfer
    [RewardAccumulationHook] --> [Claimable]: Claim available\nrewards that\nhas vested
}

node "Governance" {
    [Configuration] --> [FeeConfig]
    [Treasury]--> StakingReward: Transfer LP, PBLO\nor other token rewards
}
----

TODO: What to do for part of protocol fees that should be transferred to treasury eventually as treasury does not stake it's PBLO?

*Concerns*

* I think the vested transfer approach would limit us from implementing variable rate rewards as we see in other similar dex incentive schemes. So I think it's best that we just keep the reward rate as a parameter for LP/PBLO/PICA.. staking for each asset type instead of doing vested transfers
* The staking-rewards pallet with the current setup would be a bottleneck in doing 12h or less disbursements.

=== Pallet-Pablo

In order to 1. support LP staking 2. LP trading fee distribution and 3. PBLO staking reward using trading fees, following changes are proposed for https://github.com/ComposableFi/composable/tree/main/frame/pablo[Pallet-Pablo].

[#_feeconfig]
==== FeeConfig

Each pool in Pablo defines a fee percentage to be charged for each trade.Except for LBPs other pools also define an owner fee that is a percentage out of the main trading fee. The `FeeConfig` is a new abstraction over all fees that could be charged on a pool to allow for extension. At this time a 100% of the owner fee should be defined as a new field `protocol_fee`.

[plantuml,images/pablo-fee-config,png]
----
class FeeConfig {
    +fee_rate: Permill
    +owner_fee_rate: Permill,
    +protocol_fee_rate: Permill,
}
----

*Existing code must be modified to use this data structure*.

Given this,
----
fee = // calculation depends on the pool type: based on the fee_rate
owner_fee = fee * owner_fee_rate * (1 - protocol_fee_rate);
protocol_fee = owner_fee * protocol_fee_rate;
----
For all pools launched at the Picasso launch following values would be set for these configs
----
owner_fee_rate = 20%
protocol_fee_rate = 100% // all owner fees goes to composable to be distributed as rewards
----

==== LP Trading Fee Distribution

LPs trading fees are calculated and kept as part of the pool liquidity in Pablo. When LPs remove liquidity from the pool the trading fees are automatically redeemed according their pool LP ratio, check https://hackmd.io/@HaydenAdams/HJ9jLsfTz#Fee-Structure[reference]. This results in trading fee share being diluted overtime for smaller pools as follows.

[stem]
++++
"After " n " trades and " m " liquidity additions,"

"trading fees" = sum a_n

"total liquidity" = sum l_m

"fees and liquidity returned for an LP amount l" = l / (sum l_m) * (sum l_m + sum a_n)

= l + l / (sum l_m) * sum a_n

"trading fees received" = x = l / (sum l_m) * sum a_n

"When pool size " sum l_m " increases the amount of trading fees received " x " reduces for a particular LP position."

"For large pool sizes of " sum l_m " (steady state) this effect is negligible, hence it's a good enough strategy to distribute fees."

"But if required this effect can be negated by increasing the trading fee by a " delta a_n " while at the same time subtracting it from the total fees paid out already to liquidity providers as follows,"

"New trading fee " = x_(adjusted) = l / (sum l_m) * (sum a_n + delta a_n)

"For " r_(th) " liquidity provider,"

delta a = (sum_(r+1) l_m) / (sum l_r) * sum a_n

= x_(adjusted) = l_(r) / (sum_(r+1) l_m + sum l_r) * (sum a_n + (sum_(r+1) l_m) / (sum l_r) * sum a_n )

= l_r / (sum l_r) * sum a_n

"With this adjusted value all later additions to LP shares have been negated when receiving fees for earlier LPs."


++++

[#_pblo_staker_trading_fee_distribution]
==== PBLO Staker Trading Fee Distribution

This is the reward a `PBLO` staker receives from the trading fees of Pablo pools. It is equal to the protocol fee charged on Pablo pools. This can be accomplished by calling the already existing `StakingReward.transfer_reward` interface as follows. According to product there is also a need to convert whatever the fee asset in to PBLO to create a demand/additional value for PBLO.

[plantuml,images/pablo-fNFT-pblo-staking-fee-distro,png]
----
start
->after Pablo swap,
fee=x,
fee token=QUOTE,
from = transaction_origin;
:swap x of QUOTE to y of PBLO;
note left: how to avoid fee\nswap recursion? \n I wonder if we really need this?
:StakingReward::transfer_reward(
asset=PBLO,
reward_asset: PBLO
from=transaction_origin,
amount=y,
keep_alive=false
);
stop
----

Will it need a change in https://github.com/ComposableFi/composable/blob/main/frame/composable-traits/src/staking_rewards.rs#L96[this] ?

=== Pallet Staking Rewards - LP/PICA/PBLO/Other Token Staking Reward Pools

This section covers how the staking rewards are distributed using the https://github.com/ComposableFi/composable/tree/main/frame/staking-rewards[staking rewards pallet].

==== Analysis of Reward Calculations

In order to create the necessary reward pool as well as the rewarding rate for stakers the following model can be used. It tries to address the following constraints

. Allow addition of new stakers at anytime to a pool, start earning immediate rewards
. Allow more realtime calculation of rewards on-demand for a given pool for a given user.
. Allow shorter reward pool calculation epoch with the use of the reward rate.
. Allow specification of reward rate for a pool (even setting a dynamically changing rate)
. Allow expansion of rewards pools realtime.

[stem]
++++
"Let's define the following terms for a given staking reward pool,"

"Pre-defined reward rate (say per second)" = r

"Pre-defined reward calculation epoch in seconds" = t

"Reward per calculation epoch" = r.t

"Previous total reward pool before the current epoch" = P

"Assuming there is a per epoch calculation which adds to the pool,"
"the total reward pool for the current epoc,"

P_(current) = P + rt

"Reward pool shares for n stakers"

= sum (s_n)

"Where " n_(th) " staker share is " s_n

"Existing " n_(th) " staker reward,"

x _n = P_(current) . s_n / (sum s_n)

------------------------------------------------

"When adding a new staker n+1, existing stakers(n) reward would be,"

x_n = P_(current) . s_n / (sum s_(n+1))

"As this is less than what is expected above, an adjustment " delta P " to total reward pool can be made to allow realtime reward calculations,"

delta P = P_(current) . s_(n+1) / (sum s_n)

x_n = (P_(current) + delta P) . s_n / (sum s_(n+1))

x_n = P_(current) . (1 + s_(n+1) / (sum s_n)) . s_n / (sum s_(n+1))

x _n = P_(current) . s_n / (sum s_n)

"**Therefore existing staker receives the same reward as before.**"


"To compensate for this new adjustment, a reduction " d_(n + 1) " of reward for each staker needs to be tracked,"

x_(n+1) = P_(current) . s_(n+1) / (sum s_(n+1)) - d_(n+1)

"In general"

d_n = "Any reduction in reward including already claimed"

------------------------------------------------

"When adding a new reward to the pool the calculations remain the same other than,"

P_(current) = P + rt + P_(added)

"Since already claimed rewards("d_n") are tracked for each staker, "

"they can always claim the new reward share from " P_(added) " later."

++++

As this method uses a reward pooling based approach to calculate the rewards for each staker out of it on-demand, rest of the document refers to this as the "reward pooling(*RP*) based approach".

==== Data Structures

Staking rewards pallet already uses the following fNFT data structure,

[source,rust]
----
include::../frame/composable-traits/src/staking_rewards.rs[lines=103..122]
----
This data structure can be modified to support the RP approach by adding/adjusting/removing some fields.

[source,rust]
----
pub struct StakingNFT<AccountId, AssetId, Balance, Epoch, Rewards> {
/// The staked asset.
pub asset: AssetId,
/// The original stake this NFT was minted for.
/// Used for calculating the pool share.
pub stake: Balance,

/// New: Pool share received for this NFT
pub share: Balance,

/// New: reduced rewards for the fNFT (d_n)
pub reduction: Balance,

/// The reward epoch at which this NFT will start yielding rewards. This is no longer needed.
/// pub reward_epoch_start: Epoch,

/// List of reward asset/pending rewards. This is no longer needed as pending rewards are pooled
/// pub pending_rewards: Rewards,

/// The date at which this NFT was minted.
pub lock_date: Timestamp,

/// The duration for which this NFT stake was locked.
pub lock_duration: DurationSeconds,

/// The penalty applied if a staker unstake before the end date.
pub early_unstake_penalty: Penalty<AccountId>,

/// The reward multiplier. Can remove this and calculate the extra shares a user gets based on the multiplier
/// pub reward_multiplier: Perbill,
}
----

[#_rewardaccumulationhook]
==== RewardAccumulationHook

Following algorithm is to added as part of the existing https://github.com/ComposableFi/composable/blob/main/frame/staking-rewards/src/lib.rs#L363[block hook] in staking rewards pallet. As it is only accumulating new rewards for an upcoming epoch, the code is proposed to be run inside a new state `State:AccumulatingRewards`.

[plantuml,images/staking-rewards-reward-accumulation-hook,png]
----
start
->State:AccumulatingRewards;
:rewardConfigIndex = read(rewardConfigCount) - 1;
repeat :rewardConfig = read(rewardConfigs[rewardConfigIndex--]);
    :reward_allocation = Assets::balance_of(reward_allocation_acc,
            rewardConfig.asset);
    :epochReward = reward_allocation * rewardConfig.reward_rate;
    :stakerReward = epochReward;
    :perAssetRewardAllocationIndex = read(perAssetRewardAllocationCount) - 1;
    repeat :lpRewardAllocation = read(perAssetRewardAllocation[perAssetRewardAllocationIndex--]);
        :lpEpochReward = EpochReward * lpRewardAllocation;
        :staking_rewards::transfer_reward(
            lpRewardAllocation.asset,
            rewardConfig.asset,
            reward_allocation_acc,
            lpEpochReward, false);
        :stakerReward -= lpEpochReward;
    backward:perAssetRewardAllocationIndex;
    repeat while (perAssetRewardAllocationIndex != -1)
    :staking_rewards::transfer_reward(
        rewardConfig.asset,
        rewardConfig.asset,
        reward_allocation_acc,
        stakerReward, false);
    note left: remainder after the per\nasset allocation is\ntransferred to same\nasset stakers reward
backward:rewardConfigIndex;
repeat while (rewardConfigIndex != -1)
stop
----

This algorithm runs in `O(staked_asset_type_count * rewarded_asset_type_count)`.

== Implementation

=== Pallet Pablo: LP Fee + Staking Changes

- [ ] Implement <<_feeconfig>> on pallet-pablo across all 3 types of pools.
- [ ] Implement <<_pblo_staker_trading_fee_distribution>>.

=== Pallet Staking Rewards: PICA/PBLO Staking Related Changes

- [ ] Implement <<_rewardaccumulationhook>>.

[appendix]
== Fee Distribution Q&A

Based on the current setup following questions arise when deciding on the distribution of these fees to relevant liquidity providers, owners and stakers.

. A Protocol Fee for all pools in Pablo (or even protocol pallets other than Pablo)?
+
Does it make sense to define a protocol fee percentage on top of the pool owner fees of the pools so that the protocol fee can be used as the pot out of which the stakers are rewarded? Initially the Protocol Fee = Pool Owner Fee as the pools are owned by Composable. Assumption here is that the stakers would indeed still get a reward out of third party created pool fees.
+
*Comment:* While having a protocol funding mechanism is valuable, initially the protocol fees should zero or minimal.
. How does the system reward PICA stakers? Wouldn't the Pablo protocol needs some parameter to define how much of its swap fee or protocol fee as referred to above would go to PICA holders? Or do we assume that PICA stakers do not get a reward out of the Pablo pool fees?
.. If Pablo does reward PICA stakers, the system might need a common interface that directs those funds out of Pablo.
.. If Pablo does reward PICA stakers, the system might need to have a treasury parameter that defines the percentage that goes out to PICA holders that can be adjusted overtime.
+
*Comment:* PICA stakers would not be rewarded from the Pablo fees. PICA stakers are rewarded in newly minted PICA(or PBLO later), Mechanism to transfer the PICA tokens for stakers does not exist, need to be built.
. Does it make sense to define a Pool Owner Fee(Protocol Fee as referred to above) for LBPs that goes out to Pablo holders reward pool?

*Comment:* Pool fees could be swapped to PBLO token before distributing to fNFT holders unless those fees are in some pre-defined set of currencies(eg: KSM, DOT), which creates a demand for PBLO since the system is buying back PBLO. But for this there should be a market for PBLO/the other token that is being earned as fees.

*Comment:* LP fees can be distributed based on the fNFT. Minting the fNFT at the time of LP event might make sense. i.e fNFT represents the LP position on the pool as well as the rewards position for PBLO tokens for LPs.
