{
 "title": "ComposableCollator",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Block Production Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "rate(substrate_block_height{chain=\"picasso\", instance=\"composable_node:9615\", status=\"finalized\"}[1m])",
     "legendFormat": "Blocks per minute"
    }
   ]
  },
  {
   "title": "Networking bytes per minute",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "rate(substrate_sub_libp2p_network_bytes_total{chain=\"picasso\", instance=\"composable_node:9615\", job=\"composable_collator\"}[1m])",
     "legendFormat": "{{direction}}"
    }
   ]
  },
  {
   "title": "Height of the chain",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "substrate_block_height{chain=\"picasso\", instance=\"composable_node:9615\", job=\"composable_collator\"}",
     "legendFormat": "{{status}}"
    }
   ]
  },
  {
   "title": "Finality Lag",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "substrate_block_height{status=\"best\", chain=\"picasso\", instance=\"composable_node:9615\"} - on() substrate_block_height{status=\"finalized\", chain=\"picasso\", instance=\"composable_node:9615\"}",
     "legendFormat": "finality lag"
    }
   ]
  },
  {
   "title": "Node CPU usage",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(container_cpu_usage_seconds_total{container_label_com_docker_compose_service=\"composable_node\", instance=\"cadvisor:8080\", name=\"composable_node\"}[$__rate_interval])*100",
     "legendFormat": "{{cpu}}"
    }
   ]
  },
  {
   "title": "Netstat Packages",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(substrate_sub_libp2p_network_bytes_total{chain=\"picasso\", instance=\"composable_node:9615\"}[$__rate_interval])",
     "legendFormat": "{{direction}}"
    }
   ]
  },
  {
   "title": "Running Tasks",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "rate(substrate_tasks_polling_started_total{chain=\"picasso\", instance=\"composable_node:9615\"}[$__rate_interval])",
     "legendFormat": "{{task_name}}"
    }
   ]
  },
  {
   "title": "Peers Count",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 4, "x": 12, "y": 24 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "substrate_sub_libp2p_peers_count{chain=\"picasso\", instance=\"composable_node:9615\"}",
     "legendFormat": "peers count"
    }
   ]
  },
  {
   "title": "Connected Peers",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 16, "y": 24 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "substrate_sync_peers{chain=\"picasso\", instance=\"composable_node:9615\"} ",
     "legendFormat": "Connected Peers"
    }
   ]
  },
  {
   "title": "Peers Discovered",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 20, "y": 24 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "substrate_sub_libp2p_peerset_num_discovered{chain=\"picasso\", instance=\"composable_node:9615\"} ",
     "legendFormat": "Peers Discovered"
    }
   ]
  },
  {
   "title": "Number of Leaves",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 30 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "substrate_number_leaves{chain=\"picasso\", instance=\"composable_node:9615\"}",
     "legendFormat": "number_leaves"
    }
   ]
  },
  {
   "title": "Tasks Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "targets": [
    {
     "expr": "rate(substrate_tasks_spawned_total{chain=\"picasso\", instance=\"composable_node:9615\"}[$__interval])",
     "legendFormat": "{{task_name}}"
    }
   ]
  },
  {
   "title": "DB cache ",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 38 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "substrate_state_db_cache_bytes{chain=\"picasso\", instance=\"composable_node:9615\"}",
     "legendFormat": "{{subtype}}"
    }
   ]
  },
  {
   "title": "Container Ram Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 40 },
   "targets": [
    {
     "expr": "container_memory_usage_bytes{container_label_com_docker_compose_service=\"composable_node\", instance=\"cadvisor:8080\", job=\"cadvisor\", name=\"composable_node\"}*0.00000095367432",
     "legendFormat": "ram usage mb"
    }
   ]
  },
  {
   "title": "Synced Peers",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 46 },
   "targets": [
    {
     "expr": "substrate_sync_peers{chain=\"picasso\", instance=\"composable_node:9615\"}",
     "legendFormat": "synced pears"
    }
   ]
  },
  {
   "title": "Queued Blocks",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 48 },
   "targets": [
    {
     "expr": "substrate_sync_queued_blocks{chain=\"picasso\", instance=\"composable_node:9615\"}",
     "legendFormat": "queued blocks"
    }
   ]
  }
 ]
}