{
 "title": "Composable Collator Monitoring",
 "description": "substrate network node metrics",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Height of the chain",
   "type": "stat",
   "gridPos": { "h": 6, "w": 14, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "substrate_block_height{chain=\"picasso\", instance=\"composable_node:9615\", job=\"composable_collator\", status=\"best\"}",
     "legendFormat": "{{status}}"
    }
   ]
  },
  {
   "title": "Networking bytes per second",
   "type": "stat",
   "gridPos": { "h": 6, "w": 10, "x": 14, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "substrate_sub_libp2p_network_bytes_total{chain=\"picasso\", instance=\"composable_node:9615\", job=\"composable_collator\"}",
     "legendFormat": "{{instance_name}}"
    }
   ]
  },
  {
   "title": "Block Height",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 6 },
   "targets": [
    {
     "expr": "substrate_block_height{chain=\"picasso\", instance=\"composable_node:9615\", job=\"composable_collator\"}",
     "legendFormat": "best blocks"
    }
   ]
  },
  {
   "title": "Synced Peers",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 6 },
   "targets": [
    {
     "expr": "substrate_sync_peers{chain=\"picasso\", instance=\"composable_node:9615\"}",
     "legendFormat": "{{instance_name}}"
    }
   ]
  },
  {
   "title": "Block production rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 14 },
   "targets": [
    {
     "expr": "rate(substrate_block_height{chain=\"picasso\", instance=\"composable_node:9615\", status=\"best\"}[1m])",
     "legendFormat": "{{status}}"
    }
   ]
  },
  {
   "title": "Finality lag",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 14 },
   "targets": [
    {
     "expr": "substrate_block_height{status=\"best\", chain=\"picasso\", instance=\"composable_node:9615\"} - on() substrate_block_height{status=\"finalized\", chain=\"picasso\", instance=\"composable_node:9615\"}",
     "legendFormat": "finality lag"
    }
   ]
  },
  {
   "title": "Node memory usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "container_memory_usage_bytes{container_label_com_docker_compose_config_hash=\"ac00d83eb58543dad5df0f7b8d8a2b3357a0f2e1522b98c69c749b3e1b1d8e0d\", container_label_com_docker_compose_container_number=\"1\", container_label_com_docker_compose_oneoff=\"False\", container_label_com_docker_compose_project=\"composable\", container_label_com_docker_compose_project_config_files=\"docker-compose.yml\", container_label_com_docker_compose_project_working_dir=\"/home/ubuntu/composable\", container_label_com_docker_compose_service=\"composable_node\", container_label_com_docker_compose_version=\"1.29.2\", id=\"/docker/ae942ef8ecad8d6ca1effff377888a261bf28389594ee5ad599705e3136299c4\", image=\"composable_composable_node\", instance=\"cadvisor:8080\", job=\"cadvisor\", name=\"composable_node\"}\n\n",
     "legendFormat": "{{instance_name}}/{{env}}"
    }
   ]
  },
  {
   "title": "Node CPU usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "rate(container_cpu_usage_seconds_total{container_label_com_docker_compose_service=\"composable_node\", image=\"composable_composable_node\", instance=\"cadvisor:8080\", name=\"composable_node\"}[$__rate_interval])*100"
    }
   ]
  },
  {
   "title": "Tasks rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(substrate_tasks_spawned_total{chain=\"picasso\", instance=\"composable_node:9615\"}[$__interval])",
     "legendFormat": "{{instance_name}}/{{task_name}}"
    }
   ]
  },
  {
   "title": "Running Tasks",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(substrate_tasks_polling_started_total{chain=\"picasso\", instance=\"composable_node:9615\"}[$__rate_interval])",
     "legendFormat": "{{task_name}}"
    }
   ]
  },
  {
   "title": "Peers connected, discovered, and requested",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "substrate_sub_libp2p_peerset_num_discovered{chain=\"picasso\", instance=\"composable_node:9615\"} ",
     "legendFormat": "Peers Discovered"
    }
   ]
  },
  {
   "title": "Connected peers",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "substrate_sync_peers{chain=\"picasso\", instance=\"composable_node:9615\"}"
    }
   ]
  },
  {
   "title": "Load Avg",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 46 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "container_cpu_load_average_10s{container_label_com_docker_compose_service=\"composable_node\",instance=\"cadvisor:8080\"}"
    }
   ]
  },
  {
   "title": "Netstat",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 46 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(substrate_sub_libp2p_network_bytes_total{chain=\"picasso\", instance=\"composable_node:9615\"}[$__rate_interval])"
    }
   ]
  },
  {
   "title": "State Cache DB",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 54 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "substrate_state_db_cache_bytes{chain=\"picasso\", instance=\"composable_node:9615\"}"
    }
   ]
  },
  {
   "title": "Number of transactions in the ready queue",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 54 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "substrate_ready_transactions_number{chain=\"picasso\", instance=\"composable_node:9615\"}"
    }
   ]
  },
  {
   "title": "State Cache",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 62 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "substrate_state_cache_bytes{chain=\"picasso\", instance=\"composable_node:9615\"}"
    }
   ]
  },
  {
   "title": "Queued Blocks (sync)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 62 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "substrate_sync_queued_blocks{chain=\"picasso\", instance=\"composable_node:9615\"}"
    }
   ]
  },
  {
   "title": "Number of Peers",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 70 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "substrate_sub_libp2p_peers_count{chain=\"picasso\", instance=\"composable_node:9615\"}"
    }
   ]
  },
  {
   "title": "Number of Leaves",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 70 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "substrate_number_leaves{chain=\"picasso\", instance=\"composable_node:9615\"}"
    }
   ]
  }
 ]
}