[env]
CARGO_MAKE_EXTEND_WORKSPACE_MAKEFILE = true
NIGHTLY_VERSION = "2022-04-18"

[tasks.fmt]
script = '''
cargo +nightly fmt
'''
workspace = false

[tasks.build]
args = ["build", "--release"]
workspace = false

[tasks.polkadot]
script = '''
if [ ! -d "../polkadot" ] ; then
    git clone -b v0.9.27 https://github.com/paritytech/polkadot ../polkadot
fi
cd ../polkadot && cargo build --release 
'''
workspace = false

[tasks.start-devnet]
dependencies = ["build", "git-polkadot"]
script = '''
cargo run --release -- --version
cd ../polkadot && cargo run --release -- --version && pwd && cd ../composable
cd scripts/polkadot-launch && yarn && yarn composable
'''
workspace = false

[tasks.start-devnet-docker]
dependencies = []
script = '''
docker run --rm -ti -u$(id -u):$(id -g) -p9944:9944 -p9988:9988 -p9998:9998 composablefi/composable-sandbox:latest
'''
workspace = false

[tasks.remove-composable-sandbox-image]
dependencies = []
script = '''
docker rmi composablefi/composable-sandbox:latest
'''
workspace = false

[tasks.run-unit-tests]
env = { SKIP_WASM_BUILD = 1 }
script = '''
cargo test --workspace --locked --release --verbose
'''
workspace = false

[tasks.style]
script = '''
make style
'''
workspace = false

[tasks.run-local-integration-tests-debug]
description = "fastest way to build and debug runtime in simulator"
env = { RUST_BACKTRACE = "full", RUST_LOG = "trace,parity-db=warn,trie=warn,runtime=trace,substrate-relay=trace,bridge=trace,xcmp=trace,xcm=trace", SKIP_WASM_BUILD = 1 }
script = '''
cargo +stable test --package local-integration-tests --features local-integration-tests --features picasso --no-default-features -- --nocapture --test-threads=1
'''
workspace = false

[tasks.check-ci]
env = { SKIP_WASM_BUILD = 1 }
script = '''
cargo +nightly-$NIGHTLY_VERSION check --benches --all --features runtime-benchmarks # checks all rust crates with default-features, tests, benchmarks
env -u RUSTFLAGS cargo +nightly-$NIGHTLY_VERSION clippy --all-targets --tests -- -D warnings
'''
workspace = false

[tasks.build-benchmarks]
script = '''
cargo build --release --features runtime-benchmarks
'''
workspace = false
