[env]
CARGO_MAKE_EXTEND_WORKSPACE_MAKEFILE = true
NIGHTLY_VERSION = "2022-04-18"

[tasks.fmt]
script = '''
cd code
cargo +nightly fmt
'''
workspace = false

[tasks.build]
script = '''
cd code
cargo build --release
'''
workspace = false

[tasks.polkadot]
script = '''
if [ ! -d "../polkadot" ] ; then
    git clone -b v0.9.30 https://github.com/paritytech/polkadot ../polkadot
fi
cd ../polkadot && cargo build --release
'''
workspace = false

[tasks.start-devnet]
dependencies = ["build", "git-polkadot"]
script = '''
cd code
cargo run --release -- --version
cd ../polkadot && cargo run --release -- --version && pwd && cd ../composable
cd scripts/polkadot-launch && yarn && yarn composable
'''
workspace = false

[tasks.start-devnet-docker]
dependencies = []
script = '''
docker run --rm -ti -u$(id -u):$(id -g) -p9944:9944 -p9988:9988 -p9998:9998 composablefi/composable-sandbox:latest
'''
workspace = false

[tasks.remove-composable-sandbox-image]
dependencies = []
script = '''
docker rmi composablefi/composable-sandbox:latest
'''
workspace = false

[tasks.run-unit-tests]
env = { SKIP_WASM_BUILD = 1 }
script = '''
cd code
cargo test --workspace --locked --release --verbose
'''
workspace = false

[tasks.style]
script = '''
make style
'''
workspace = false

[tasks.check-ci]
env = { SKIP_WASM_BUILD = 1 }
script = '''
cd code
cargo +nightly-$NIGHTLY_VERSION check --benches --all --features runtime-benchmarks # checks all rust crates with default-features, tests, benchmarks
env -u RUSTFLAGS cargo +nightly-$NIGHTLY_VERSION clippy --all-targets --tests -- -D warnings
'''
workspace = false

[tasks.build-benchmarks]
script = '''
cd code
cargo build --release --features runtime-benchmarks
'''
workspace = false
