@startuml
skinparam responseMessageBelowArrow true
title Vamm creation
'autoactivate on
!theme mars

participant "Client" as client
participant "Vamm" as vamm
database "Storage (Vamm)" as svamm
database "Blockchain" as bc

client -> vamm++: Create market request
vamm -> svamm: Create market
vamm -->o bc: Deposit created market event
vamm --> client--: New market ID
@enduml
