= Protocol Specification: Financial Non-Fungible Tokens (fNFT)
:math:
:stem:
:imagesoutdir: images
:imagesdir: images
:toc:
:toclevels: 4
:sectnums:
:sectnumlevels: 4


|===
|Revision |Date |Comment |Author

|v0.1
|2022-08-13
|Draft version
|Vim

|===

== Abstract

This document describes the specification for the Composable Finance's Financial Non-Fungible Tokens (fNFT) protocol.


== Background

https://en.wikipedia.org/wiki/Non-fungible_token[Non-fungible tokens(NFT)] stored in a blockchain is commonly used to represent ownership of some asset. For example one of the most popular use cases of these is the representation of ownership of a piece of digital art like in the case of https://www.larvalabs.com/cryptopunks[crypto punks]. A public blockchain as an immutable ledger allows trading of these assets as financial securities. Ethereum's https://eips.ethereum.org/EIPS/eip-721[ERC-721] specification is one popular attempt at standardizing these assets for Ethereum ecosystem using its smart contracts. Standardization allows these assets to be used in a wide variety of use cases in an interoperable way including in popular marketplaces.

The perceived value of an NFT as an asset can vary based on what underlying asset it represents. Composable Finance intends to define a protocol that allows standardization of operations on those underlying assets. The motivation is to increase interoperability and the compatibility of these NFT assets across the broader ecosystem where Composable Finance intends to become a major asset originator.


== Goals

The following goals are defined to enable a common standard compatible with any https://wiki.polkadot.network/docs/learn-crosschain[cross consensus messaging(XCM)] compatible blockchain, that allows representation of a financial position as an fNFT asset.

. The fNFT asset MUST be transferable between accounts(owners) without the underlying position being mutated in an unintended way.
. The owner(account) of the fNFT asset MUST be allowed to perform actions that mutate the position according to what's allowed by the asset originating protocol. For example claiming yield for a yield baring asset.
. The asset originating protocol MUST be able to avoid a direct dependency on ownership details of the fNFT asset for its internal operations.
. The fNFT assets MUST be reusable across any other ecosystem protocols that want to use them. Eg: An fNFT market would be able to publish a complying NFT asset originating from any other fNFT protocol in its catalog.

=== Example Use Cases

==== Staking

In the following example a staker receives a fNFT to represent their staking position, which can be freely traded like any other financial asset.

[plantuml,images/staking-fnft,png]
----
skinparam usecase {
BackgroundColor YellowGreen

ArrowColor Olive
}
left to right direction
actor Staker as p
actor StakeBuyer as r

package StakingProtocol {
    usecase "1. Stake Assets" as UC1
    usecase "2. Mint fNFT" as UC2
    usecase "3. Earn Rewards/Get slashed on fNFT" as UC3
    usecase "4. Split/Sell/Transfer fNFT" as UC4
    usecase "5. Receive fNFT" as UC5
    usecase "6. Earn Rewards/Get slashed on fNFT" as UC6
}

p -up-> UC1
p -up-> UC2
p -up-> UC3
p -up-> UC4
r -up-> UC5
r -up-> UC6
----

==== Debt Instruments

In the following example a debt instrument is created and sold buy a borrower as an fNFT to a lender. Whoever owns the fNFT receives the interest payments and the principle at the end of the loan term.

[plantuml,images/debt-fnft,png]
----
skinparam usecase {
BackgroundColor YellowGreen

ArrowColor Olive
}
left to right direction
actor Borrower as p
actor Lender as r

package BondingProtocol {
    usecase "1. Mint Bond as fNFT" as UC1
    usecase "2. Sell Bond fNFT" as UC2
    usecase "3. Receive Loan" as UC3
    usecase "4. Buy Bond as fNFT" as UC4
    usecase "5. Receive Interest Payments" as UC5
}

p -up-> UC1
p -up-> UC2
p -up-> UC3
r -up-> UC4
r -up-> UC5
----

==== Coin Voting Based on fNFT Ownership

In the following example an fNFT with locked assets that has voting power is bought by a voter. Again whoever owns the fNFT receives the voting power of the underlying assets.

[plantuml,images/coin-voting-fnft,png]
----
skinparam usecase {
BackgroundColor YellowGreen

ArrowColor Olive
}
left to right direction
actor VoteBuyer as p

package CoinVotingProtocol {
    usecase "1. Buy fNFT with Locked Assets with Voting Power" as UC1
    usecase "2. Vote with fNFT Assets" as UC2
    usecase "3. Split/Sell/Transfer fNFT" as UC3
}

p -up-> UC1
p -up-> UC2
p -up-> UC3
----

== Specification

This specification consists of two main parts as the following diagram shows:

[plantuml,images/spec-parts,png]
----
package "1. Financial NFT Traits" {
    namespace frame_support::traits::tokens::nonfungibles {
        interface i as "Inspect" {
            itemId
            collectionId: AssetId
        }
        interface c as "Create"
        interface m as "Mutate"
    }


    interface f as "FinancialNFT" {
        asset_account()
        get_next_nft_id()
    }

    frame_support::traits::tokens::nonfungibles.i <|-- f
}

package "2. Financial NFT Protocol Trait" {
    interface fp as "FinancialNFTProtocol" {
        collection_asset_ids(): [AssetId]
        value_of()
    }
}

fp o-- f : "Financial NFT Protocol aggregates\nand controls the fNFTs identified\nby `collection_asset_ids()`"
----

The diagram can be summarized as,

_A Financial NFT protocol provides access to value owned by a Financial NFT that belongs to a collection ID included in the list of collection asset IDs it exposes._

The following subsections dives into the specification of the main two parts illustrated.

NOTE: The interfaces are shown in Rust language syntax for convenience to be used in https://docs.substrate.io/[Substrate] though they can be readily translated into any other programming language.

=== Financial NFT Traits

Substrate framework already defines https://paritytech.github.io/substrate/master/frame_support/traits/tokens/nonfungibles/index.html[nonfungibles] traits to be implemented by pallets that create, read, update and delete NFT assets in a generally reusable way. This specification extends one of those traits to allow for inspection of fNFT assets when implemented by a NFT pallet.

[source,rust]
----
/// Inspect trait from substrate shown for completeness
pub trait Inspect<AccountId> {
    /// Type for identifying a fNFT.
    type ItemId;
    /// Type for identifying a collection (an identifier for an
    /// independent collection of items).
    /// For fNFTs the NFT collection Id should be set as a unique asset ID
    /// for the type of financial asset it represents. This allows
    /// the fNFT protocols to identify asset types it controls.
    type CollectionId;

    fn owner(
        collection: &Self::CollectionId,
        item: &Self::ItemId
    ) -> Option<AccountId>;

    // ...
}

/// Wrap any financial position into the ownership of an NFT
trait FinancialNFT<AccountId>: Inspect<AccountId> {

    /// ID of the Account which holds the assets owned by a financial NFT. The value of the
    /// financial NFT is the sum total of balances of all asset types in this account plus the
    /// future returns minus any liabilities. Future returns and liabilities should be queried
    /// through the originating financial NFT protocol.
    fn asset_account(collection: &Self::CollectionId, instance: &Self::ItemId) -> AccountId;

    /// Retrieve the next valid financial NFT ID for the given collection in order to
    /// mint a new NFT.
    fn get_next_nft_id(collection: &Self::CollectionId) -> Result<Self::ItemId, DispatchError>;
}
----

The important thing of note is the introduction of the asset account concept for each fNFT.

==== Asset Account

Instead of the fNFT owner account controlling any assets controlled by the fNFT, asset account serves as an indirection holding the assets owned by a financial NFT. This allows for the fNFT to be transferred between owners without the owners having the ability to mutate the assets in an unintended way. The fNFT originating protocol instead defines the level of control and actions that an owner could take. i.e. fNFT protocol ultimately controls the assets according to its design.

=== Financial NFT Protocol Trait

The following trait must be implemented by any fNFT asset originating protocol.

[source,rust]
----
/// Trait to be implemented by protocol supporting financial NFTs.
pub trait FinancialNFTProtocol {
    /// Type for identifying an item.
    type ItemId;

    /// Asset ID type. This is the type used for financial NFT collection IDs. Following
    /// https://github.com/paritytech/xcm-format#6-universal-asset-identifiers setting collection
    /// IDs as asset IDs (asset class), allows universal identifiers for all asset classes
    /// across eco system projects. Refer xcm::..::MultiLocation
    type AssetId;

    /// Balance type.
    type Balance;

    /// Returns the set of Asset IDs mapping the originated financial NFT collections to
    /// the financial NFT protocol. Used to identify the financial NFT protocol to route
    /// operations related to a given financial NFT.
    ///
    /// Eg: for staking rewards if
    ///  the fNFT collectionId(assetId) of issued fNFTs for staking positions of a particular reward
    ///  pool a is x and for another b is y. Then this function returns vec![x, y].
    fn collection_asset_ids() -> Vec<Self::AssetId>;

    /// The value of the financial NFT is the sum total of balances of all asset types in its
    /// account plus the future returns minus any liabilities.
    ///
    /// - collection: id of the financial NFT collection issued/used by the protocol.
    fn value_of(
        collection: &Self::AssetId,
        instance: &Self::ItemId,
    ) -> Vec<(Self::AssetId, Self::Balance)>;
}
----

=== Cross Consensus Messaging(XCM) Concerns

Polkadot specifies XCM format to allow for communication between parachains or more broadly between any consensus system like a blockchain. fNFTs are designed to be compatible between any system that complies with XCM messaging format. This requires compliance with https://github.com/paritytech/xcm-format/blob/master/README.md#format[MultiAsset] specification. Following is the specification of a MultiAsset format for a fNFT.

* `class: Concrete`
** `location: MultiLocation` - The location can be specified in two ways.
... By addressing the fNFT asset account:
.... `parents:` relative navigation
.... `InteriorMultiLocation:` Vec[Parachain, AccountId32]
... By addressing the fNFT protocol
.... `parents:` relative navigation
.... `InteriorMultiLocation:` Vec[Parachain, PalletInstance, GeneralIndex(fNFT CollectionId), GeneralKey(fNFT ItemId)]
* `fun: NonFungible`

NOTE: This section may change based on any changes made to XCM format.

== Implementation

First reference implementation of the specification is the staking position fNFTs in the https://github.com/ComposableFi/composable/tree/main/frame/staking-rewards[pallet-staking-rewards(Financial NFT Protocol)] together with https://github.com/ComposableFi/composable/tree/main/frame/fnft[pallet-fnft (Financial NFT)].

Pallet-fnft uses https://wiki.polkadot.network/docs/learn-proxies[substrate account proxies] to set the owning account of a fNFT as a proxy for its asset account for governance actions in the runtime(eg: Picasso parachain). This should serve as an example of extending functionality available to an fNFT owner beyond what the basic `frame_support::traits::tokens::nonfungibles` traits allow.

== References
. Non-fungible tokens(NFT) - https://en.wikipedia.org/wiki/Non-fungible_token
. Crypto punks - https://www.larvalabs.com/cryptopunks
. ERC-721 - https://eips.ethereum.org/EIPS/eip-721
. cross consensus messaging(XCM) - https://wiki.polkadot.network/docs/learn-crosschain
. Substrate - https://docs.substrate.io/
. Substrate nonfungibles traits - https://paritytech.github.io/substrate/master/frame_support/traits/tokens/nonfungibles/index.html
. MultiAsset addresses - https://github.com/paritytech/xcm-format/blob/master/README.md#format
. Substrate account proxies - https://wiki.polkadot.network/docs/learn-proxies
