= Design Document: Apollo Price Oracle
:math:
:stem:
:imagesoutdir: images
:imagesdir: images
:toc:
:toclevels: 4
:sectnums:
:sectnumlevels: 4

== Abstract

This is a post-facto engineering design document for the Apollo price oracle. Apollo oracle serves price information from out of consensus sources such as exchanges into the Picasso DeFi ecosystem.

== Background

Composable Finance plans to launch a decentralized price oracle to support the DeFi ecosystem in the Picasso parachain called Apollo. Apollo would provide access to asset prices from various price feeds coming from both centralized and decentralized off-chain sources such as decentralized/centralized exchanges. Bringing off-chain prices on-chain requires solving the infamous oracle problem.

=== What is the Oracle Problem?

The oracle problem in blockchains occur because of the need for pieces of logic running on a blockchain such as smart contracts to access off-chain data sources that do not fall within blockchain consensus and verifiability by definition and hence would not be natively "trustworthy" as they could be manipulated. For example if a smart contract running on Picasso parachain wants to access the price of ETH token it would require getting that price from an exchange such as Binance or Uniswap. But that runs the risk of the price being manipulated by the provider of the data or the original source itself causing the smart contract logic to derive wrong results. Avoiding this problem requires either implementing a) a fully trusted centralized oracle or b) a decentralized oracle. While the centralized approach could work for a variety of use cases, when designing a large DeFi ecosystem such as Picasso it's not the right choice as the oracle could become the weakest element in terms of security in the system.

=== Decentralized Price Oracles

A decentralized price oracle provides certain guarantees that a provided price is accurate and free of manipulation by employing a decentralized set of price providers instead of a single centralized one.
Refer https://hal.archives-ouvertes.fr/hal-03620931/document[[1]] or https://research.chain.link/whitepaper-v2.pdf[[2]] for more thorough coverage of the topics involved.

== Requirements

=== Utility

. Oracle MUST be configurable to provide prices for required assets types for the Picasso parachain DeFi ecosystem.
. Oracle MUST provide interfaces for any other on-chain protocol on Picasso to integrate with it to get price updates.
. Oracle MUST provide interfaces for any off-chain protocol such as a front end app to integrate with it to get price updates.
. Oracle system MUST be extensible to provide additional statistics on top of the Oracle prices such as time weighted average price(TWAP).

=== Accuracy (Observation Integrity)

Working under the assumption of an honest majority of Oracle providers,

. Oracle prices MUST be accurate to within a pre-defined level of error from the market consensus.
. Oracle prices MUST be resistant to temporary glitches in accuracy faced by a minority of the Oracle providers.

=== Security

Working under the assumption of an honest majority of Oracle providers,

. Oracle prices MUST be resistant to manipulation by an Oracle price provider.
. Oracle prices MUST be resistant to manipulation by a third party.
. Oracle MUST be resistant to denial of service attacks. i.e prices MUST be available at all required intervals.
. Oracle MUST be resistant to front-running.

=== Scalability

. The system MUST provide prices in the desired frequency(every `n` blocks) with low latency for the required asset types (Liveliness).
. The system MUST scale to be able to provide prices for any number of assets that Picasso DeFi ecosystem requires.

=== Decentralization

. The system MUST support the number of Oracle providers that governance deems necessary for the decentralization of the protocol.
. The system MUST support a wide variety of price sources.

== Method

=== System Overview

Following diagram illustrates an overview of the Apollo design with some minor components skipped over for clarity.

.Apollo Price Oracle: The System Overview
[plantuml,images/apollo-overview,png]
----
skinparam interface {
  backgroundColor RosyBrown
  borderColor orange
}

skinparam node {
  backgroundColor<<parachain>> TECHNOLOGY
}

skinparam package {
  backgroundColor LightCyan
}

skinparam cloud {
  backgroundColor Azure
}

skinparam node {
  backgroundColor<<price-source>> Lavender
}

skinparam databaseBackgroundColor SkyBlue

cloud "Oracle Provider Infra" <<oracle-infra>> {
    node "Picasso Parachain Node" <<parachain>> {
        () "Oracle" as o
        package "Pallet Apollo" {
            Database "PrePrices" as preprice_db
            Database "AssetsInfo" as asset_db
            Database "OracleStake" as stake_db
            Database "Prices" as price_db
            Database "PriceHistory" as pricehistory_db
            Database "RewardTrackerStore" as reward_db
            [Offchain Worker] as ofw
            [on_init hook] as oih
            () "SubmitPrice" as sp
            () "AdjustRewards" as ar
            () "AddStake" as as
            () "AddAssetAndInfo" as adda
            ar --> reward_db
            ofw --> sp
            sp --> preprice_db
            oih <-- preprice_db
            adda --> asset_db
            asset_db --> oih
            oih --> price_db
            oih <--> stake_db : read/slash
            as --> stake_db
            oih --> pricehistory_db
        }

        ["Governance"] --> ar
        ["Governance"] --> adda
        reward_db --> oih : block reward
        price_db --> o
        pricehistory_db --> o
    }

    package "Price Feed Server" <<price-feed>> {
        () "Rest API" as price_api
        database "Price Cache" as pc
        () "Client 1 - Binance Client" as c1
        () "Client 2 - Pyth Client" as c2
        () ".. Client n" as cn

        pc --> price_api
        c1 --> pc: price feed
        c2 --> pc: price feed
        cn --> pc: price feed
        c1 <.up.> binance
        c2 <.up.> pyth
        cn <.up.> n
    }
}

ofw <.left.> price_api : get price

cloud {
    node "Price-Source 1 - Binance" <<price-source>> as binance {
    }
}

cloud {
    node "Price-Source 2 - Pyth" <<price-source>> as pyth {
    }
}

cloud {
    node ".. Price-Source n" <<price-source>> as n {
    }
}

"Oracle Provider" as op
op -up-> as
----

NOTE: It is proposed to rename the existing pallet-oracle as pallet-apollo here.

The following sections drill down into these components and others in more detail.

=== Component: Pallet Apollo
==== Data Structure: Price

Represents a price of an asset accepted by the Oracle.
[plantuml,images/price,png]
----
class Price {
	price: PriceValue,
	block: BlockNumber,
}

note left of Price::block
The block the price
was submitted at.
end note
----

==== Data Structure: PrePrice

Represents a price submitted by an Oracle provider.

[plantuml,images/pre-price,png]
----
class PrePrice {
    price: PriceValue,
    block: BlockNumber,
    who: AccountId,
}

note left of PrePrice::price
The price of an asset,
normalized to 12 decimals.
end note

note left of PrePrice::block
The block the price
was submitted at.
end note

note left of PrePrice::who
The account that
submitted the price.
end note
----

==== Data Structure: AssetInfo

Represents the asset information for an asset that prices would be tracked for in the oracle.

[plantuml,images/asset-info,png]
----
class AssetInfo {
    threshold: Percent,
    min_answers: u32,
    max_answers: u32,
    block_interval: BlockNumber,
    reward_weight: Balance,
    slash: Balance,
}

note left of AssetInfo::threshold
accuracy in terms of a
percentage of median price.
This measure needs review
& improvement.
end note

note left of AssetInfo::min_answers
minimum number of
submitted pre-prices
required for this asset type.
end note

note left of AssetInfo::max_answers
maximum number of
submitted pre-prices
accepted for this asset type.
end note

note left of AssetInfo::block_interval
Expected frequency of
updates to the price.
end note

note left of AssetInfo::reward_weight
Reward allocation weight
for this asset type out
of the total block reward.
end note

note left of AssetInfo::slash
Amount slashed for submitting
a price beyond the
accepted error threshold
end note

----

==== Storage: AssetsInfo

----
asset_info = Map<AssetId, AssetInfo>
----

==== Storage: Prices

----
prices = Map<AssetId, Price>
----

==== Storage: PrePrices

----
pre_prices = Map<AssetId, Array<PrePrice>>
----

==== Storage: PriceHistory

----
price_history = Map<AssetId, Array<Price>>
----

==== Storage: OracleStake

----
oracle_stake = Map<AccountId, Balance>
----

==== Storage: RewardTrackerStore

For further details refer https://github.com/ComposableFi/composable/blob/main/frame/oracle/design/rewards/rewards-design.md[rewards-design].

==== Interface: Oracle

===== get_price

[source,rust]
----
fn get_price(asset_id: Self::AssetId, amount: Self::Balance, ) -> Result<Price<Self::Balance, Self::Timestamp>, DispatchError>;
----

TODO: Algo

===== get_twap_for_amount

[source,rust]
----
fn get_twap_for_amount(asset_id: Self::AssetId, amount: Self::Balance) -> Result<Self::Balance, DispatchError>;
----

TODO: Algo

===== get_ratio

[source,rust]
----
fn get_ratio(pair: composable_traits::defi::CurrencyPair<Self::AssetId>) -> Result<sp_runtime::FixedU128, DispatchError>;
----
TODO: Algo

===== get_price_inverse

[source,rust]
----
fn get_price_inverse(asset_id: Self::AssetId, amount: Self::Balance) -> Result<Self::Balance, DispatchError>;
----

TODO: Algo

==== Interface: Pallet Extrinsics

===== add_asset_and_info

[source,rust]
----
pub fn add_asset_and_info(
			origin: OriginFor<T>,
			asset_id: T::AssetId,
			threshold: Validated<Percent, ValidThreshold>,
			min_answers: Validated<u32, ValidMinAnswers>,
			max_answers: Validated<u32, ValidMaxAnswer<T::MaxAnswerBound>>,
			block_interval: Validated<T::BlockNumber, ValidBlockInterval<T::StalePrice>>,
			reward_weight: BalanceOf<T>,
			slash: BalanceOf<T>,
		) -> DispatchResultWithPostInfo;
----

TODO: Algo

===== set_signer

[source,rust]
----
pub fn set_signer(
			origin: OriginFor<T>,
			signer: T::AccountId,
		) -> DispatchResultWithPostInfo;
----

TODO: Algo

===== adjust_rewards

[source,rust]
----
pub fn adjust_rewards(
			origin: OriginFor<T>,
			annual_cost_per_oracle: BalanceOf<T>,
			num_ideal_oracles: u8,
		) -> DispatchResultWithPostInfo;
----

TODO: Algo

===== add_stake

[source,rust]
----
pub fn add_stake(origin: OriginFor<T>, stake: BalanceOf<T>) -> DispatchResultWithPostInfo;
----

TODO: Algo

===== remove_stake

[source,rust]
----
pub fn remove_stake(origin: OriginFor<T>) -> DispatchResultWithPostInfo;
----

TODO: Algo

===== reclaim_stake

[source,rust]
----
pub fn reclaim_stake(origin: OriginFor<T>) -> DispatchResultWithPostInfo;
----

TODO: Algo

===== submit_price

[source,rust]
----
pub fn submit_price(
			origin: OriginFor<T>,
			price: T::PriceValue,
			asset_id: T::AssetId,
		) -> DispatchResultWithPostInfo;
----


.Extrinsic: SubmitPrice
[plantuml,images/extrinsic-submit-price,png]
----
start
->origin, price, asset_id;
:author = ensure origin is signed;
:author_stake = OracleStake.get(author);
:ensure is_requested;
note left: refer algorithm for is_requested\nin Offchain Worker
:ensure author_stake >= config[min_stake] + AnswerInTransit[author];
note left
an answer in transit
could be slashed later
hence it has to be taken
into account.
end note
:asset_info = AssetInfo[asset_id];
:ensure asset_info.slash <= author_stake;
:current_prices = PrePrices[asset_id];
:ensure length of current_prices < asset_info.max_answers;
:ensure current_prices does not contain
a price submitted by the author;
:current_prices.append(price);
:AnswerInTransit[author] += asset_info.slash;
:publish PriceSubmitted Event;
end
----

==== Algorithm: Offchain Worker

.Offchain Worker: check_requests
[plantuml,images/offchain-worker,png]
----
start
while (asset_id, asset_info = AssetsInfo.iter().next())
  if (1. is_requested(asset_id)) then (yes)
    :2. fetch_price_and_send_signed(asset_id, asset_info);
  endif
endwhile
stop
----

Following are the sub-procedures from above main algorithm,

.Offchain Worker: is_requested
[plantuml,images/offchain-worker-1-is-requested,png]
----
start
->asset_id;
:last_update = prices[asset_id];
:asset_info = asset_info[asset_id];
if (exists asset_info ?) then (yes)
    :return
    last_update.block
    + asset_info.block_interval
    < current_block;
    note left: Price is requested if\nthe last update is too old
    stop
else (no)
    :return false;
    stop
endif
----

.Offchain Worker: fetch_price_and_send_signed
[plantuml,images/offchain-worker-2-fetch-price-and-send-signed,png]
----
start
->asset_id, asset_info;
:signer = all available keys in key_store;
:oracle_account_id = read_key_store();
:asset_info = asset_info[asset_id];
:prices = pre_prices[asset_id];
if (signer can not sign)
    :Error: No Local accounts to sign;
elseif (length of prices > asset_info.max_answers) then (yes)
    :Error: Maximum number of answers provided;
    stop
elseif (prices has price with\nwho=oracle_account_id) then (yes)
    :Error: Price already submitted by the Oracle;
    stop
else
    :price = fetch_price(asset_id);
    note right: Fetch price from the\nlocal price feed server
    :signed_extrinsic = sign with signer:
    extrinsic submit_price(asset_id, price);
    :call signed_extrinsic;
endif
stop
----

==== Algorithm: on_initialize Hook

.on_initialize: update_prices
[plantuml,images/on-initialize-1-update-prices,png]
----
start
->block;
:total_weight = 0;
while (asset_id, asset_info = AssetsInfo.iter().next())
    :ok, pre_prices, removed_pre_prices_len = update_pre_prices(asset_id, asset_info, block);
    if (ok) then (yes)
        :total_weight += removed_pre_prices_len;
        :update_price(asset_id, asset_info, block, pre_prices);
    endif
endwhile
end
----

This algorithm is `O(A * P)` Where `A` = number of assets tracked and `P` = number of prices. This possibly requires optimization to scale so that it won't take up the entire block weight.

.update_prices: update_pre_prices prunes PrePrices storage
[plantuml,images/update-prices-1-update-pre-prices,png]
----
start
->asset_id, asset_info, block;
if (length of PrePrices[asset_id] > asset_info.min_answers) then (yes)
    :staled_prices, pruned_prices = prune_old_pre_prices(asset_info, PrePrices[asset_id], block);
    :for each staled_prices emit AnswerPruned;
    :PrePrices[asset_id] = pruned_prices;
endif
end
----

.update_pre_prices: prune_old_pre_prices prunes PrePrices storage based on stale_price config
[plantuml,images/update-pre-prices-1-prune-old-prices,png]
----
start
->asset_info, pre_prices, block;
:stale_block = block - config[stale_price];
note left
A price is considered
stale of it was
submitted earlier
than stale_block
end note
:stale_prices, fresh_prices = pre_prices, [];
while (index, p = pre_prices.next())
    if (p.block >= stale_block) then (yes)
        :remove_price_in_transit(p.who, asset_info);
        :stale_prices, fresh_prices = split pre_prices from split index to end;
    endif
endwhile
:fresh_prices = fresh_prices[0..asset_info.max_answers];
:return stale_prices, fresh_prices;
end
----

NOTE: `AnswerInTransit` is used to calculate the minimum stake required to submit a price. Refer submit_price extrinsic.

.update_prices: update_price calculates and updates the actual asset price based on the already pruned pre_prices.
[plantuml,images/update-prices-2-update-price,png]
----
start
->asset_id, asset_info, block, pre_prices;
if (length of pre_prices > == asset_info.min_answers) then (yes)
    :price = calculate_price(pre_prices, asset_info);
    :Prices[asset_id] = price;
    if (length of PriceHistory > config[max_history]) then (yes)
        :remove PriceHistory[asset_id][0];
    endif
    :PriceHistory[asset_id].append(price);
endif
end
----

.update_price: calculate_price calculates the actual price for asset
[plantuml,images/update-price-1-calculate-price,png]
----
start
->pre_prices,asset_info;
:median_price = get_median_price(pre_prices);
:sum_of_prices, number_of_prices = 0;
while(answer = pre_prices.next())
    :accuracy = (median_price - abs(answer - median_price)) / median_price * 100;
    if (accuracy >= asset_info.threshold) then
        :sum_of_prices += answer;
        :number_of_prices++;
    endif
endwhile
:return sum_of_prices / number_of_prices;
end
----

.calculate_price: get_median_price calculates the median price for an asset among pre-prices
[plantuml,images/calculate-price-1-get-median-price,png]
----
start
->pre_prices;
:numbers = [];
while (pre_price = pre_prices.next())
    :numbers.append(converted pre_price);
endwhile
:quick_sort(numbers);
:mid = numbers.len() / 2;
if (numbers.len() % 2 == 0) then (yes)
    :median = numbers[mid - 1] + numbers[mid] / 2;
else
    :median =  numbers[mid];
endif
:return median;
end
----

.update_price: handle_payout pays the reward out
[plantuml,images/update-price-2-handle-payout,png]
----
start
->pre_prices, price, asset_id, asset_info;
:rewarded_oracles = [];
while(answer = pre_prices.next())
    :accuracy = (median_price - abs(answer - median_price)) / median_price * 100;
    note left: Can improve on this statistic
    if (accuracy < asset_info.threshold) then
        :OracleStake[answer.who] -= asset_info.slash;
        :transfer slash_amount to treasury;
    else
        :rewarded_oracles.append(answer.who);
    endif
endwhile
:reward_tracker = RewardTrackerStore.value;
:reward_amount_per_oracle = reward_tracker.current_block_reward *
asset_info.reward_weight / reward_tracker.total_reward_weight;
:transfer reward_amount_per_oracle to all rewarded_oracles;
end
----

For further details on rewarding refer https://github.com/ComposableFi/composable/blob/main/frame/oracle/design/rewards/rewards-design.md[rewards-design].

=== Component: Price Feed Server

==== Interface: Price Feed Client

TODO

==== Interface: Rest API

TODO

=== Security and Price Accuracy Model

TODO

- Manipulation range without getting slashed?
- How much of bribe it takes for an Oracle provider to provide the wrong price?
- Chance of collusion
- Nothing at stake?
- Ensuring continuous function?

=== Becoming an Oracle Provider

TODO flow chart of the process

==== Key Management

TODO

== Rollout

== Future Improvements

* [ ] Measure and improve on_initialize algorithm to use less block weight(possibly reusing some of the looping logic) or use a block fold abstraction when processing prices.
* [ ] Use a better statistical measure(standard deviation?) when assessing accuracy compare threshold of a provided price by an oracle.
* [ ] Possibly set maximum on `AssetInfo.max_answers` field. Use the field to short circuit the any additional logic that might be performed unnecessarily on pre_prices.
* [ ] Improve the median for price accuracy calculation.
* [ ] Make the price server easily extensible by rewriting it in typescript. Ideally any party from the community should be able to integrate price-feeds into the price-server with the least possible effort.

== References

. Distributed Blockchain Price Oracle. https://hal.archives-ouvertes.fr/hal-03620931/document
. Chainlink 2.0: Next Steps in the Evolution of Decentralized Oracle Networks. https://research.chain.link/whitepaper-v2.pdf
. Apollo docs. https://docs.composable.finance/products/the-picasso-parachain/the-picasso-tech-stack/apollo
