@startuml

box Composable #LightYellow
  participant "Assets" as pallet_assets
  participant "Lending" as pallet_lending
  participant "Dutch Auction" as pallet_dutch_action
  control "OCW Liquidation" as ocw_liquidation
end box

box HydraDx #SkyBlue
  participant "HydraDx" as pah
  participant "HydraDx Auction" as pauh
end box

ocw_liquidation -> pallet_lending: Detect liquidate condition
ocw_liquidation -> pallet_lending: Liquidate

alt OB
  pallet_lending --> pah: XCM sell via 'Transfer' + 'Exchange'
  ...
  alt Sold
    pah --> pallet_assets: XCM 'Transfer' sold out back
  else Fatal fail to sell
    pah --> pallet_assets: XCM: `Transfer' + `ReportError`
  end
else Dutch Auction
  pallet_lending --> pallet_dutch_action: XCM sell via 'Transfer' + 'Transact'
  note over pah
    - will share `Dispatchable` `Call` `Extrinsic` contract
  end note
end

@enduml
