@startuml

box Composable #LightYellow
  participant "Assets" as pas
  note over pas
    - all mappings are immutable (until all trades are gone for them)
  end note
  participant "Accounts" as pa
  participant "Composable Sudo" as pac
  note over pac
    - for now mapping proposal is single user,
    - so can be voted later via Dispatchable Call
  end note

end box

box Composable #SkyBlue
  participant "HydraDx" as pah
end box

pah --> pa : Create account

pac -> pas: Approve Hydra Account to be mapping provider

pac -> pas: Add new mapping

pah -> pas: Approve mapping


@enduml
