export default {
  types: {
    ComposableTraitsAssetsXcmAssetLocation: "Null",
    PalletCrowdloanRewardsModelsRemoteAccount: {
      _enum: {
        RelayChain: 'AccountId32',
        Ethereum: 'EthereumAccountId'
      }
    },
    ComposableTraitsCallFilterCallFilterEntry: "Null",
    PalletAssetsRegistryCandidateStatus: "Null",
    SpConsensusAuraSr25519AppSr25519Public: "Null",
    ComposableTraitsBondedFinanceBondOffer: "Null",
    PalletCollatorSelectionCandidateInfo: "Null",
    PalletCrowdloanRewardsReward: "Null",
    PalletDemocracyVoteThreshold: "Null",
    PalletDemocracyPreimageStatus: "Null",
    PalletDemocracyReferendumInfo: "Null",
    PalletDemocracyReleases: "Null",
    PalletDemocracyVoteVoting: "Null",
    CumulusPalletDmpQueueConfigData: "Null",
    PalletDutchAuctionSellOrder: "Null",
    ComposableTraitsVestingVestingSchedule: "Null",
    CumulusPalletDmpQueuePageIndexData: "Null",
    PalletDutchAuctionTakeOrder: "Null",
    ComposableTraitsGovernanceSignedRawOrigin: "Null",
    PalletIdentityRegistration: "Null",
    PalletIdentityRegistrarInfo: "Null",
    PalletOracleAssetInfo: "Null",
    PalletOracleWithdraw: "Null",
    PalletOraclePrePrice: "Null",
    PalletOraclePrice: "Null",
    PolkadotPrimitivesV1AbridgedHostConfiguration: "Null",
    CumulusPalletParachainSystemRelayStateSnapshotMessagingStateSnapshot: "Null",
    PolkadotPrimitivesV1PersistedValidationData: "PersistedValidationData",
    PalletSchedulerScheduledV2: "Null",
    PalletSchedulerReleases: "Null",
    DaliRuntimeOpaqueSessionKeys: "Null",
    OrmlTokensAccountData: "Null",
    OrmlTokensBalanceLock: "Null",
    PalletTreasuryProposal: "Null",
    PalletVaultModelsStrategyOverview: "Null",
    PalletVaultModelsVaultInfo: "Null",
    CumulusPalletXcmpQueueInboundStatus: "Null",
    PolkadotParachainPrimitivesXcmpMessageFormat: "Null",
    CumulusPalletXcmpQueueOutboundStatus: "Null",
    CumulusPalletXcmpQueueQueueConfigData: "Null",
    PalletCrowdloanRewardsModelsProof: {
      _enum: {
        RelayChain: '(AccountId32, MultiSignature)',
        Ethereum: 'EcdsaSignature'
      }
    },
    PalletDemocracyConviction: "Null",
    PalletDemocracyVoteAccountVote: "Null",
    ComposableTraitsDefiSell: "Null",
    ComposableTraitsAuctionAuctionStepFunction: "Null",
    ComposableTraitsDefiTake: "Null",
    PalletIdentityJudgement: "Null",
    PalletIdentityBitFlags: "Null",
    PalletIdentityIdentityInfo: "Null",
    CumulusPrimitivesParachainInherentParachainInherentData: 'ParachainInherentData',
    DaliRuntimeOriginCaller: "Null",
    ComposableTraitsVaultVaultConfig: "Null",
    XcmVersionedMultiAsset: "Null",
  }
};
