@startuml
skinparam handwritten true


box "Parachain Composable"
actor Composable as ac
participant "Assets" as pa
participant "Vault" as pv
participant "Order Book DEX" as pd
control "OCW Order Book DEX" as cd
actor Polkadex as ap
end box

boundary "Parachain Polkadex" as bp

ac -> pd : Create order with white list of satisfying account ids (default is any)
pd -> pa : Trasfer collateral
note right
  creates future order is active for several blocks
end note

' priviliged - burn collateral
' 2 priveleged - option over people (still need on chain)
' later on on pribileged - mint (with some prove - may previos mints did good)
' later -  mint, set order cleaned
'

' -----
' not priveleged - should deposit before


{block_start} bp --> pd: Get orders with promise to be active for several block
bp --> pv: Transfer borrow via bridge
bp --> pd : Send borrow account
{block_end}  pd -> pa : Burn collateral
bp --> bc : Check prove collateral was burnt


@enduml
