@startuml


actor Composable as ac
actor Polkadex as ap
participant "Assets" as pa
boundary "Parachain Polkadex" as bp
boundary "Parachain Composable" as bc
participant "Vault" as pv
participant "Order Book DEX" as pd
control "OCW Order Book DEX" as cd

ac -> pd : Create order with white list of satisfying account ids (default is any)
pd -> pa : Trasfer collateral
note right
  creates future order is active for several blocks
end note


{block_start} bp --> pd: Get orders with promise to be active for several block
bp --> pv: Transfer borrow
bp --> pd : Send borrow account
{block_end}  pd -> pa : Burn collateral
bp --> bc : Check prove collateral was burnt
{block_start} <-> {block_end} : 3 blocks, or what next?

@enduml
