import { getEnvironment } from "shared/endpoints";
import { SubstrateNetwork, SubstrateNetworkId } from "./types";
import {
  KARURA_SUBSCAN_URL,
  KUSAMA_SUBSCAN_URL,
  PICASSO_SUBSCAN_URL,
  STATEMINE_SUBSCAN_URL,
} from "@/defi/config";

export const SUBSTRATE_NETWORKS: {
  [substrateNetworkId in SubstrateNetworkId]: SubstrateNetwork;
} = {
  kusama: {
    relayChain: "kusama",
    parachainId: 0,
    name: "Kusama",
    wsUrl: getEnvironment("kusama"),
    tokenId: "ksm",
    ss58Format: 2,
    subscanUrl: KUSAMA_SUBSCAN_URL,
    decimals: 12,
    symbol: "KSM",
    logo: "/networks/kusama.svg",
  },
  picasso: {
    relayChain: "kusama",
    parachainId: 2087,
    name: "Picasso",
    wsUrl: getEnvironment("picasso"),
    tokenId: "pica",
    ss58Format: 49,
    subscanUrl: PICASSO_SUBSCAN_URL,
    decimals: 12,
    symbol: "PICA",
    logo: "/networks/picasso.svg",
  },
  karura: {
    relayChain: "kusama",
    parachainId: 2000,
    name: "Karura",
    wsUrl: getEnvironment("karura"),
    tokenId: "kar",
    ss58Format: 8,
    subscanUrl: KARURA_SUBSCAN_URL,
    decimals: 12,
    symbol: "KAR",
    logo: "/networks/karura.svg",
  },
  statemine: {
    relayChain: "kusama",
    parachainId: 1000,
    name: "Statemine",
    wsUrl: getEnvironment("statemine"),
    tokenId: "ksm",
    ss58Format: 2,
    subscanUrl: STATEMINE_SUBSCAN_URL,
    symbol: "KSM",
    logo: "/networks/statemine.svg",
    decimals: 12,
  },
};
export const SUBSTRATE_NETWORK_IDS: Array<SubstrateNetworkId> = Object.keys(
  SUBSTRATE_NETWORKS
) as Array<SubstrateNetworkId>;

export const getSubstrateNetwork = (
  networkId: SubstrateNetworkId
): SubstrateNetwork => SUBSTRATE_NETWORKS[networkId];

/**
 * TODO: move to utils or substrate-react
 * @param network picasso, karura or kusama
 * @param extrinsicHash extrinsic hash generated by polkadot js
 * @returns link to subscan
 */
export function subscanExtrinsicLink(
  network: SubstrateNetworkId,
  extrinsicHash: string
): string {
  return SUBSTRATE_NETWORKS[network].subscanUrl + "extrinsic/" + extrinsicHash;
}
