pub use pallet::*;

#[frame_support::pallet]
pub mod pallet {
	use codec::Codec;
	use composable_traits::{
		oracle::{Oracle, Price},
		vault::Vault,
	};
	use frame_support::pallet_prelude::*;
	use sp_runtime::{ArithmeticError, FixedPointNumber};
	use sp_std::fmt::Debug;

	use crate::mocks::{Balance, MockCurrencyId};

	#[pallet::config]
	pub trait Config: frame_system::Config {
		type VaultId: Clone + Codec + Debug + PartialEq + Default + Parameter;
		type Vault: Vault<AssetId = MockCurrencyId, VaultId = Self::VaultId, Balance = Balance>;
	}

	#[pallet::pallet]
	#[pallet::generate_store(pub(super) trait Store)]
	pub struct Pallet<T>(_);

	#[pallet::storage]
	#[pallet::getter(fn btc_value)]
	pub type BTCValue<T: Config> = StorageValue<_, u128, ValueQuery>;

	impl<T: Config> Pallet<T> {
		pub fn get_price(of: MockCurrencyId) -> Result<Price<Balance, ()>, DispatchError> {
			<Self as Oracle>::get_price(of)
		}
		pub fn set_btc_price(price: u128) {
			BTCValue::<T>::set(price)
		}
	}

	impl<T: Config> Oracle for Pallet<T> {
		type AssetId = MockCurrencyId;
		type Balance = Balance;
		type Timestamp = ();

		fn get_price(
			of: Self::AssetId,
		) -> Result<Price<Self::Balance, Self::Timestamp>, DispatchError> {
			let usd_mul = |k| {
				Self::get_price(MockCurrencyId::USDT)
					.map(|Price { price, block }| Price { price: price * k, block })
			};
			match of {
				/*
					Ideally we would have all the static currency quoted against USD cents on chain.
					So that we would be able to derive LP tokens price.
				*/
				MockCurrencyId::USDT => Ok(Price { price: 100, block: () }),
				MockCurrencyId::PICA => usd_mul(10),
				MockCurrencyId::BTC => usd_mul(Self::btc_value()),
				MockCurrencyId::ETH => usd_mul(3000),
				MockCurrencyId::LTC => usd_mul(200),
				/*
					If we want users to be able to consider LP tokens as currency,
					the oracle should know the whole currency system in order to
					recursively resolve the price of an LP token generated by an
					arbitrary level of vaults.

					The base asset represented by the level 0 (out of LpToken case)
					should have a price defined.

					One exception can occur if the LP token hasn't been generated by a vault.
				*/
				x @ MockCurrencyId::LpToken(_) => {
					let vault = T::Vault::token_vault(x)?;
					let base = T::Vault::asset_id(&vault)?;
					let Price { price, block } = Self::get_price(base)?;
					let rate = T::Vault::stock_dilution_rate(&vault)?;
					let derived = rate
						.checked_mul_int(price)
						.ok_or(DispatchError::Arithmetic(ArithmeticError::Overflow))?;
					Ok(Price { price: derived, block })
				},
			}
		}

		fn get_twap(
			_of: Self::AssetId,
			_weights: Vec<u128>,
		) -> Result<Self::Balance, DispatchError> {
			Ok(0u32.into())
		}
	}
}
