@startuml Add margin
!theme mars

actor "Trader" as user
participant "Clearing\nHouse" as CH
database "AccountsMargin" as CHS
collections "Collateral\naccount" as Acc

user -> CH : add margin

CH -> CH : ensure collateral is supported

CH -> CH ++: Deposit collateral
    CH -> user : transfer to\nClearing House
    user -> Acc : collateral
return

CH -> CHS : get/create margin account

CH -> CHS : update margin amount

?<-o CH : emit event
@enduml