@startuml close_position
!theme mars

title Closing a Position

actor "Trader" as user
participant "Clearing\nHouse" as ch
participant "vAMM" as vamm
participant "Risk\nEngine" as risk
database "Markets" as mkts
database "Positions" as positions
database "AccountsMargin" as accs
collections "Collateral\naccount" as vault
collections "Fees\naccount" as fees

user -> ch : ""close_position""

== Storage updates ==

ch -[#green]> mkts : get ""Market""
ch -[#green]> positions : get position
'note right CH: compute quote asset\nnotional amount

group settle funding payments?
ch -[#red]> accs : update collateral
end

ch -> vamm ++ : swap base for quote asset
return quote asset amount

ch -[#red]> accs : realize PnL

ch -[#red]> positions : delete position
ch -[#red]> mkts : update open interest

group charge fee
ch -[#red]> accs : subtract fee from user's collateral
end

note right ch
update funding rate?
end note

== Validity checks ==

note right ch
block trade if it pushes
the mark price far from
the oracle?
end note

== Asset transfers ==

group charge fee
ch -> vault : transfer to Fee Pool
vault -> fees : quote asset
end

====

?<-o ch : emit event
@enduml
