@startuml close_position
!theme mars

title Closing a Position

actor "Trader" as user
participant "Clearing\nHouse" as ch
participant "vAMM" as vamm
database "Markets" as mkts
database "Positions" as positions
database "Collateral" as accs

user -> ch : ""close_position""

== Storage updates ==

ch -[#green]> mkts : get ""Market""
ch -[#green]> positions : get position
'note right CH: compute quote asset\nnotional amount

group settle funding payment
ch -[#red]> accs : update collateral
end

ch -> vamm ++ : swap base for quote asset
return quote asset amount

ch -[#red]> accs : realize PnL

ch -[#red]> positions : delete position
ch -[#red]> mkts : update open interest

group charge fee
ch -[#red]> accs : subtract fee from user's collateral
ch -[#red]> mkts : add fee to market Fee Pool
end

ch -[#red]> mkts : try updating funding rate

== Validity checks ==

note right ch
block trade if it pushes
the mark too far from
the oracle price
end note

?<-o ch : emit event
@enduml
