@startuml create_market
actor "god" as g
participant "Clearing\nHouse" as ch
participant "trait\nInstruments" as inst
database "Markets" as markets
participant "vAMM" as vamm
participant "Oracle" as oracle 

g -> ch : ""create_market""

ch -> oracle : check has price feed for ""AssetId""

ch -> vamm : ""create""
return ""VammId""

ch -> ch : get new market id

ch -> markets : store ""Market"" struct

ch -> inst ++: ""update_funding""
inst -> vamm: fetch TWAP
inst -> oracle: fetch TWAP
inst -> markets : update\n""cum_funding_rate""
return

?<-o ch : emit event
@enduml