@startuml create_market
!theme mars

actor "authority" as g
participant "Clearing\nHouse" as ch
database "Markets" as markets
participant "vAMM" as vamm
participant "Oracle" as oracle 

g -> ch : ""create_market""

ch -> oracle : check has price feed for ""AssetId""

ch -> vamm : ""create""
return ""VammId""

ch -> ch : get new market id

ch -> ch ++: initialize ""Market"" struct
ch -> ch: get current timestamp
return

ch -> markets : store ""Market"" struct

?<-o ch : emit event
@enduml