@startuml liquidate
!theme mars

actor "User/Bot" as user
participant "Clearing\nHouse" as ch
database "Positions" as positions
database "Collateral" as accs
database "Markets" as mkts
participant "vAMM" as vamm
collections "Collateral\naccount" as vault
collections "Insurance\naccount" as insurance

user -> ch: ""liquidate""

== Validy checks ==

note right ch
check oracle
guard rails?
end note

ch -> ch ++: ensure below MMR/PMR
    ch -> ch ++: compute margin ratio
        ch -[#green]> accs : get collateral
        ch -[#green]> positions : get all user positions
        loop over all positions
            ch -[#green]> mkts : get corresponding market
            ch -> vamm : get position value
        end
    return
return

== Storage updates ==

loop until margin requirement met
    ch -[#green]> positions : get next position
    ch -> ch: settle funding payments
    ch -> ch ++ : decrease/close position
       ch -> vamm : swap base for quote asset
    return
    ch -> ch : realize PnL
    ch -[#red]> mkts : update open interest
end

ch -[#red]> positions : update
ch -[#red]> accs : update

== Asset transfers ==

group Pay liquidation fee
    ch -> vault : transfer to caller's ""AccountId""
    vault -> user : collateral
end

group Seize collateral
    ch -> vault : transfer to Insurance Fund
    vault -> insurance : collateral
end

====

?<-o ch : emit event
@enduml
