@startuml liquidate
!theme mars

actor "User/Bot" as user
participant "Clearing\nHouse" as ch
participant "RiskEngine" as risk
database "Positions" as positions
database "Collateral" as accs
database "Markets" as mkts
participant "vAMM" as vamm
collections "Collateral\naccount" as vault
collections "Insurance\naccount" as insurance

user -> ch: ""liquidate""

== Validy checks ==

note right ch
check oracle
guard rails?
end note

ch -> risk ++: ensure below MMR/PMR
    risk -> risk ++: compute\nmargin ratio
        risk -[#green]> accs : get collateral
        risk -[#green]> positions : get all user positions
        risk -[#green]> mkts : get all markets\ninvested
        risk -> vamm : get prices
    return
return

== Storage updates ==

    ch -[#green]> positions : get all user positions
    ch -> vamm : swap base for quote asset
    ch -[#red]> positions : reduce/remove
    ch -[#red]> accs : realize PnL
    ch -[#red]> mkts : update open interest

== Asset transfers ==

alt Bad debt
    ch -> insurance : reimburse Clearing House
    insurance -> vault : collateral
else Seize collateral
    ch -> vault : transfer to Insurance Fund
    vault -> insurance : collateral
end

group Pay liquidation fee
    ch -> vault : transfer to caller's ""AccountId""
    vault -> user : collateral
end


====

?<-o ch : emit event
@enduml
