@startuml open_position
!theme mars
skinparam responseMessageBelowArrow true

title Opening a Position

actor "Trader" as user
participant "Clearing\nHouse" as ch
participant "vAMM" as vamm
participant "Risk\nEngine" as risk
database "Markets" as mkts
database "Positions" as positions
database "AccountsMargin" as accs
collections "Collateral\naccount" as vault
collections "Fees\naccount" as fees

user -> ch : open position

== Storage updates ==

ch -> mkts : get ""Market""
ch -> positions : get/create position
'note right CH: compute quote asset\nnotional amount

ch -> vamm ++ : swap quote for base asset
return base asset amount

ch -> ch : realize PnL?

ch -> positions : update position
ch -> mkts : update open interest

== Validity checks ==

'RiskEngine
ch -> risk ++: ensure\n""above_initial_margin_ratio""
    risk -> risk ++: compute\nmargin ratio
        risk -> accs : get margin
        risk -> positions : get all user positions
        risk -> mkts : get all markets\ninvested
        risk -> vamm : get prices
    return
return
'note right ch : ensure margin ratio\nabove MMR

note right ch : check oracle\nguard rails?

== Asset transfers ==

group charge fee
ch -> vault : transfer to Fee Pool
vault -> fees : quote asset
end

====

?<-o ch : emit event
@enduml
