@startuml update_funding
!theme mars

participant "User/Bot" as user
participant "Clearing\nHouse" as ch
participant "Instruments" as inst
database "Markets" as mkts
participant "Oracle" as oracle
participant "Vamm" as vamm

user -> ch : ""update_funding""

ch -> mkts : get market
return ""Market""

note right ch
ensure time since last update
  "">= funding_frequency""
end note

ch -> inst ++: ""funding_rate""
note right inst
ensure valid oracle?
ensure mark/oracle spread low
end note
inst -> oracle : get TWAP
note right inst
normalize oracle TWAP?
end note
inst -> vamm : get TWAP
note right inst
cap funding rate?
end note
return current funding rate

ch -> ch : add funding rate\nto market cumulative

ch -> mkts : update

?<-o ch : emit event

@enduml
