@startuml update_funding
!theme mars

actor "User/Bot" as user
participant "Clearing\nHouse" as ch
participant "Instruments" as inst
database "Markets" as mkts
participant "Oracle" as oracle
participant "vAMM" as vamm

user -> ch : ""update_funding""

ch -[#green]> mkts : get ""Market""

note right ch
ensure time since last update
  "">= funding_frequency""
end note

ch -> inst ++: ""funding_rate""
note right inst
    ensure valid oracle?
    ensure mark/oracle spread low
end note
inst -> oracle : get TWAP
note right inst
    normalize oracle TWAP?
end note
inst -> vamm : get TWAP
note right inst
    cap funding rate based on
    Fee Pool depth
end note
return current funding rate

== Storage updates ==

alt Clearing House pays funding
    note over ch, mkts
        subtract funding payment from market fee pool
    end note
else Clearing House receives funding
    note over ch, mkts
        add funding payment to market fee pool
    end note
end

note over ch, mkts
    add funding rate to market cumulative
    set funding timestamp to current time
end note
ch -[#red]> mkts : update

====

?<-o ch : emit event

@enduml
