@startuml
  actor Alice as alice
  actor Bob as bob
  actor Charlie as charlie
  participant Lending as lending
  participant Liquidation as liquidation
  control Governance as governance

  participant Vault as vault
  participant "Sell Engine" as sell
  control "OCW Lending" as lending_bot
  control "OCW Oracle" as oracle_bot

  group Governance
    alice -> lending: Create market pair for assets ids (tokens, symbols), pay rent, configure
    lending -> oracle: Check assets are supported
    lending -> vault: Create vault to store collateral asset
    ...
    governance -> vault : Allocate to Lending pair resources
    lending -> vault : Withdraw Borrowed Asset
  end

  ...

  group Borrow and Repay
    bob -> vault : Transfer collateral
    vault -> bob : Transfer cCollateral(wrapped token)
    bob -> lending : Deposit cCollateral
    ...
    bob -> lending : Borrow with collateral in price more than borrow price
    lending -> bob : Take rent for holding position
    ...
    lending -> lending : Accrue interest with each block
    ...
    bob -> lending : (Partially)repay borrow + interest
  end

  ...

  group Liquidation (IN PROGRESS)
    charlie -> lending : Borrow
    ...
    oracle_bot -> oracle : Make collateral factor bad
    lending_bot -> lending : Liquidate Charlie collateral
    lending -> liquidation: Liquidate
    liquidation -> sell: Sell via choses strategy
    note left
      - default is auction (multiblock)
      - can be DEX or external (XCMP) DEX 
      - XCMP is multi block process
    end note
    ...
    lending_bot -> lending : Finalize liquidation
  end

@enduml
